kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: monitor
  namespace: acbot-edge
spec:
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        node_type: non-leaf
      containers:
        - name: monitor
          image: 19231149/monitor:latest
          imagePullPolicy: IfNotPresent
          args:
            - '$(NODE_NAME)'
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 5201
          volumeMounts:
            - mountPath: /work/resources
              name: config
      volumes:
        - name: config
          configMap:
            name: monitor-cm