name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 构建
      run: docker build -t 19231149/dispatcher .
    - name: 上传
      run: |
        docker login --username 19231149 --password 20011013cc
        docker push 19231149/dispatcher
